# Generated by Django 3.2.25 on 2024-04-10 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='Address',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='customuser',
            name='Age',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='customuser',
            name='Gender',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='customuser',
            name='Position',
            field=models.CharField(default='', max_length=500),
        ),
    ]
