# Generated by Django 3.2.25 on 2024-05-03 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20240410_1544'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductID', models.CharField(max_length=500)),
                ('ProductName', models.CharField(max_length=500)),
                ('Category', models.CharField(max_length=500)),
                ('Description', models.CharField(max_length=500)),
                ('Qty', models.CharField(max_length=500)),
                ('BuyingPrice', models.CharField(max_length=500)),
                ('SellingPrice', models.CharField(max_length=500)),
                ('Image', models.ImageField(upload_to='product_images/')),
            ],
        ),
    ]
