# Generated by Django 3.2.25 on 2024-04-10 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_tablestocks_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tablestocks',
            name='DateTime',
        ),
    ]
